# Generated by Django 3.0.4 on 2020-03-21 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strasse', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Ort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('plz', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Laden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('inhaberName', models.CharField(max_length=40)),
                ('categorie', models.CharField(max_length=70)),
                ('phone', models.SmallIntegerField(blank=True)),
                ('mobile', models.SmallIntegerField(blank=True)),
                ('mail', models.EmailField(max_length=254)),
                ('chatEnable', models.BooleanField(default=True)),
                ('delievery', models.BooleanField(default=False)),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visch.Adresse')),
            ],
        ),
    ]
