# Generated by Django 3.0.4 on 2020-03-21 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inhaber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inhaberName', models.CharField(max_length=40)),
                ('phone', models.PositiveIntegerField(blank=True)),
                ('mobile', models.PositiveIntegerField(blank=True)),
                ('mail', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='laden',
            name='chatEnable',
        ),
        migrations.RemoveField(
            model_name='laden',
            name='inhaberName',
        ),
        migrations.RemoveField(
            model_name='laden',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='laden',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='laden',
            name='phone',
        ),
        migrations.CreateModel(
            name='Ware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laden', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='visch.Laden')),
            ],
        ),
        migrations.AddField(
            model_name='laden',
            name='inhaber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visch.Inhaber'),
        ),
    ]
